monolog:
    handlers:
        app:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_app.log"
            level: debug
            channels: ["app"]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!app","!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!app","!event", "!doctrine", "!console"]
