
home:
    path: /
    controller: App\UI\Controller\SearchController::map

map:
    path: /map
    controller: App\UI\Controller\SearchController::map

search:
    path: /search
    controller: App\UI\Controller\SearchController::search

bridge_cron_download_excel:
    path: /bridge/cron/download/excel
    controller: App\UI\Controller\BridgeCronDownloadExcelController::index

bridge_cron_process_excel:
    path: /bridge/cron/process/excel
    controller: App\UI\Controller\BridgeCronProcessExcelController::index

bridge_cron_clean_history:
    path: /bridge/cron/clean/history
    controller: App\UI\Controller\BridgeCronCleanHistoryController::index

routes_admin:
    resource: routes_admin.yaml
    name_prefix: admin_
    prefix: /admin