
home:
    path: /
    controller: App\UI\Http\Controller\Admin\AdminController::index

profile:
    path: /profile
    controller: App\UI\Http\Controller\Admin\UserController::profile

bridge:
    path: /bridge
    controller: App\UI\Http\Controller\Admin\AdminController::bridge

file_search:
    path: /file/search
    controller: App\UI\Http\Controller\Admin\FileController::search

file_delete:
    path: /file/delete/{id}
    controller: App\UI\Http\Controller\Admin\FileController::delete

station_search:
    path: /station/search
    controller: App\UI\Http\Controller\Admin\StationController::search

user_list:
    path: /user/list
    controller: App\UI\Http\Controller\Admin\UserController::list

user_view:
    path: /user/view/{id}
    controller: App\UI\Http\Controller\Admin\UserController::view

