
home:
    path: /
    controller: App\UI\Controller\Admin\AdminController::index

profile:
    path: /profile
    controller: App\UI\Controller\Admin\UserController::profile

bridge:
    path: /bridge
    controller: App\UI\Controller\Admin\AdminController::bridge

file_list:
    path: /file/list
    controller: App\UI\Controller\Admin\FileController::list

file_delete:
    path: /file/delete/{id}
    controller: App\UI\Controller\Admin\FileController::delete

station_list:
    path: /station/list
    controller: App\UI\Controller\Admin\StationController::list

user_list:
    path: /user/list
    controller: App\UI\Controller\Admin\UserController::list

user_view:
    path: /user/view/{id}
    controller: App\UI\Controller\Admin\UserController::view

